### ISSUE TITLE
我们所度过的每一个日常也许就是连续发生的奇迹 | 南柯一梦

### ISSUE THREAD

**Issue by changmenyouxi** [changmenyouxi/changmenyouxi.github.io#3]
https://changmenyouxi.github.io/quoth/

**Comment by changmenyouxi** [comment]
![](https://upload.cc/i1/2018/09/28/8rnWgv.png)

**Comment by changmenyouxi** [comment]
若你摘得小的星星，你将得到小的幸福

若你摘得大的星星，你将得到大的财富

若两者都能摘得，你将得到永远的愿望

**Comment by changmenyouxi** [comment]
想时光倒流回五年前

**Comment by nanf0621** [comment]
早安

**Comment by nanf0621** [comment]
催更。

**Comment by changmenyouxi** [comment]
昨夜重温EVA，第26回标题：在世界中心呼唤爱的野兽。日语原文为“世界の中心でアイを叫んだけもの”，出自美国科幻作家Harlan Ellison获得雨果奖的科幻小说《The Beast That Shouted Love at the Heart of the World》。回想第一次观看的光景已是2008年的暑假，十年时光荏苒，所幸少年少女们的故事还在继续。下午还要刷题，先出门吃点吧。

**Comment by changmenyouxi** [comment]
人类总要重复同样的错误。回顾断断续续准备考试的这半年，虽然有很多收获，然而后悔和惭愧的情感更胜一筹。不知这一选择所带来的后果会怎样，也许就此和包括李荇在内的许多人分道扬镳也说不定。三月的狮子中有句话：不能直视弱小的自己，被触手可及的快乐所吞噬，说的就是我这样的人吧！

**Comment by changmenyouxi** [comment]
暑假每天去河师大新554上自习的日子，现在想来说不定是自己这半年最快乐的学习时光。虽然那会新乡很热，在相当长的一段时间里气温直逼三十摄氏度，新554没有空调，只有慢悠悠的吊扇，两边窗户对开，屋里每天都有不少不怕人的麻雀在你脚边跳过去。某天晚上走出校门买水，马路对面附中的电子屏上正好滚过一句话：一切伟大的行动和思想，都有一个微不足道的开始。骑回家我把当时博客的留言板删了个干净，然后把这句话写到最顶端的位置。

**Comment by changmenyouxi** [comment]
有一星期吧，因为坐的时间过长，外加每天还出很多汗，屁股上长了坐板疮，等我感觉到的时候已经坐立难安了，想起高三被它支配的恐惧，果断选择在家里复习了，虽然大部分时间都趴在凉席上，不过效率还可以接受，这段时间玩手机比较多，也认识了不少考研的人，享受了几天家里的空调，每天睡前用盐水洗屁股，坚持了一周，屁股总算恢复了

**Comment by changmenyouxi** [comment]
八月份左右认识了李荇，十月她跑到西安学习，此前生了一次病。似乎从这里开始我俩好感渐生。现在想来，大致因为那时她和父母正在吵架，又一人在外面。而我这里和大学里一个相当重要的同学分道扬镳，直到现在也没有和解。缺乏安全感的两人距离慢慢缩短，这种方式既不纯粹也不独特，但似乎好过一个人承受琐事的煎熬。

**Comment by changmenyouxi** [comment]
我认为liz and the jade bird想描绘的是多数友情都带有的一个现实条件，那就是两个人需要处在对等的位置。所以当她们两个都在追求同一件事情时，现实的差距让她们永远没办法站到一起，这是一种巨大的压力，落后的那一方不断地陷入自我矛盾。这并不是关于什么独占欲、励志、同性相恋之类的东西，而是更加残酷却因而更加美丽的东西。我和李荇之间包含了像这样的种种矛盾

**Comment by changmenyouxi** [comment]
以前看京吹的时候，总想和高坂一样说出那句“想成为特别的人”。现在看来，无论快乐还是失败，自己都只是一个完完全全的普通人的样貌。今后还是以成为一个优秀的普通人为目标而加油吧！

**Comment by changmenyouxi** [comment]
置身事外的感受实在微妙
